services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
  prestashop:
    image: prestashop/prestashop:9.0.2
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_LANGUAGE: ${LANGUAGE:-en}
      PS_COUNTRY: ${COUNTRY:-fr}
      PS_DOMAIN: localhost:8080
      PS_HANDLE_DYNAMIC_DOMAIN: 0
      PS_FOLDER_ADMIN: admin_xxx
      ADMIN_MAIL: admin@admin.com
      ADMIN_PASSWD: admin123
