name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    - name: Install Node.js dependencies
      run: npm ci
    - name: Install PHP dependencies with Composer
      run: npm run composer:install
    - name: Start containers
      run: npm run up
    - name: Wait 60 seconds for services to be ready
      run: sleep 60
    - name: Start e2e testing
      run: npm run test
